sudo: false
language: node_js
node_js:
  - "6.7.0"
compiler: g++-4.8
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i -g angular-cli
script:
  - ng test
